# Generated by Django 5.2.8 on 2025-11-17 12:59

import core.utils.upload_img
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_city_alter_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, upload_to=core.utils.upload_img.upload_img),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('img1', models.ImageField(upload_to=core.utils.upload_img.upload_img)),
                ('img2', models.ImageField(upload_to=core.utils.upload_img.upload_img)),
                ('img3', models.ImageField(upload_to=core.utils.upload_img.upload_img)),
                ('img4', models.ImageField(upload_to=core.utils.upload_img.upload_img)),
                ('vacinado', models.BooleanField(default=False)),
                ('sexo', models.CharField(choices=[('m', 'MASCULINO'), ('f', 'FEMININO')], max_length=1)),
                ('raça', models.CharField(max_length=20)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
