# Generated by Django 5.2.8 on 2025-11-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_cpf_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
