# Generated by Django 5.2.8 on 2025-11-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacina', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='raça',
            new_name='raca',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='vacinado',
        ),
        migrations.AddField(
            model_name='pet',
            name='vacina',
            field=models.ManyToManyField(to='core.vacina'),
        ),
    ]
