# Generated by Django 5.2.8 on 2025-11-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_vacina_rename_raça_pet_raca_remove_pet_vacinado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='vacina',
            new_name='vacinas',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
