# Generated by Django 5.2.8 on 2025-11-27 17:52

import core.utils.upload_img
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_vacina_pet_vacinas_remove_pet_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='img2',
            field=models.ImageField(blank=True, upload_to=core.utils.upload_img.upload_img),
        ),
        migrations.AlterField(
            model_name='pet',
            name='img3',
            field=models.ImageField(blank=True, upload_to=core.utils.upload_img.upload_img),
        ),
        migrations.AlterField(
            model_name='pet',
            name='img4',
            field=models.ImageField(blank=True, upload_to=core.utils.upload_img.upload_img),
        ),
    ]
