# Generated by Django 5.2.8 on 2025-12-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_pet_img2_alter_pet_img3_alter_pet_img4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacina',
            old_name='vacina',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='vacina',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
