# Generated by Django 5.2.8 on 2025-12-07 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_vacina_vacina_nome_alter_vacina_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocked',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('petMatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_recebidos', to='core.pet')),
                ('petPrincipal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_bloqueios', to='core.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('petMatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_recebidos', to='core.pet')),
                ('petPrincipal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_matches', to='core.pet')),
            ],
        ),
    ]
