# Generated by Django 5.2.8 on 2025-12-07 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_blocked_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocked',
            old_name='petMatch',
            new_name='petBlock',
        ),
    ]
